server:
  port: 2333
  address: 0.0.0.0

spring:
  main:
    banner-mode: log

lavalink:
  server:
    password: "LkJhGfDsA19181716"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
  request:
    enabled: true
    includeDebugInfo: true
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
